### ISSUE TITLE
Published service-bindings v1.0.0 package is not compiled to ES5 fully

### ISSUE THREAD

**Issue by ddubson** [nebhale/client-nodejs#2]
The published [service-bindings package](https://www.npmjs.com/package/@nebhale/service-bindings) v1.0.0 does not seem to be fully compiled to ES5. After importing it into a ES6 nodejs project, attempting to import 'bindings' and 'binding' modules throws an error that they are not available:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/<user>/workspace/<project>/node_modules/@nebhale/service-bindings/bindings.js'
``` 

After further inspection, it seems like the only ES5 compiled file in the project is `index.js` and the rest are original Typescript. By entering the dependency and running `npm install` followed by `npm run build`, only then does the import work properly since the proper ES5 files are created.

Would you be able to verify that this is an issue? If so, publish a new artifact for consumption on npmjs.com?

**Comment by dsyer** [comment]
I have the same issue. Seems like the package was published manually and omitted a build step?

**Comment by nebhale** [comment]
This should be remedied in [v1.1.0](https://www.npmjs.com/package/@nebhale/service-bindings).
